### ISSUE TITLE
sbt clean doesn't call editsource:clean

### ISSUE THREAD

**Issue by RPCMoritz** [bmc/sbt-editsource#10]
According to the documentation sbt clean should also run editsource:clean. A simple test shows that this is not the case. Eith the doc should be amended with the required instructions how to achieve this, or the code needs to be looked at.
Sadly, trying to make compile also depend on (clean in EditSource) doesn't work, since the task isn't known by that name -- at least according to sbt.

**Comment by bmc** [comment]
Working for me in the latest version. Closing.
