### ISSUE TITLE
Editing doesn't happen when dependsOn

### ISSUE THREAD

**Issue by l15k4** [bmc/sbt-editsource#12]
Hey,

if I have project `A` with : 
```
    flatten in EditSource := true,
    sources in EditSource ++= (baseDirectory.value / "src/main/resources/storages" ** "*.json").get,
    targetDirectory in EditSource := (baseDirectory.value / "target" / s"scala-${scalaBinaryVersion.value}" / "classes/storages"),
    variables in EditSource += ("buildInfo", s"${name.value}-${version.value}"),
    compile in Compile := ((compile in Compile) dependsOn (edit in EditSource)).value,
```

and then project `B` with : 
```
.dependsOn(
    `A`    % "compile->compile"
  )
```

Then when building project `B`, the source editing does happen but the files contain unextrapolated variables `${buildInfo}` which means there were perhaps overriden :-/

Any idea how to enforce it? I suspect that the problem is somewhere here : 
```
"compile->compile"
```
Would you please help me out with this?

**Comment by bmc** [comment]
Should be fixed now. I used this syntax in my test project, and it worked fine:

```scala
compile in Compile := ((compile in Compile) dependsOn (edit in EditSource)).value
```
