### ISSUE TITLE
support for scala 2.12

### ISSUE THREAD

**Issue by balintn** [bmc/sbt-editsource#13]
Hi,
it would be nice to have this plugin available for sbt 1.0.2. I would like to use it with scala 2.12.3. Are you planning to update?

I tried to make it work. I put the following in my plugin.sbt:

libraryDependencies += sbtPluginExtra(
  m = "org.clapper" % "sbt-editsource" % "0.7.0",
  sbtV = "0.13",
  scalaV = "2.10"
)

but I got this error:
[error] 	java.lang.NoClassDefFoundError: sbt/SourcePosition
[error]         at org.clapper.sbt.editsource.EditSourcePlugin$.projectSettings$lzycompute(EditSourcePlugin.scala:195)
[error]         at org.clapper.sbt.editsource.EditSourcePlugin$.projectSettings(EditSourcePlugin.scala:195)
[error]         at sbt.internal.Load$.$anonfun$resolveProject$3(Load.scala:1025)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error]         at scala.collection.immutable.List.flatMap(List.scala:352)
[error]         at sbt.internal.Load$.autoPluginSettings$1(Load.scala:1025)
[error]         at sbt.internal.Load$.expandSettings$1(Load.scala:1042)
[error]         at sbt.internal.Load$.$anonfun$resolveProject$10(Load.scala:1045)
[error]         at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
[error]         at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
[error]         at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
[error]         at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error]         at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error]         at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error]         at sbt.internal.Load$.expandSettings$1(Load.scala:1044)
[error]         at sbt.internal.Load$.$anonfun$resolveProject$1(Load.scala:1048)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.resolveProject(Load.scala:1014)
[error]         at sbt.internal.Load$.finalizeProject$1(Load.scala:864)
[error]         at sbt.internal.Load$.$anonfun$loadTransitive$10(Load.scala:915)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.loadTransitive(Load.scala:915)
[error]         at sbt.internal.Load$.loadProjects$1(Load.scala:714)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$10(Load.scala:717)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:717)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:677)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:154)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:219)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error]         at sbt.internal.Load$.loadAll(Load.scala:555)
[error]         at sbt.internal.Load$.loadURI(Load.scala:485)
[error]         at sbt.internal.Load$.load(Load.scala:464)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:249)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.apply(Load.scala:249)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:65)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:696)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:696)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:688)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error]         at sbt.State$$anon$1.process(State.scala:233)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:105)
[error]         at sbt.MainLoop$.run(MainLoop.scala:98)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error]         at sbt.StandardMain$.runManaged(Main.scala:104)
[error]         at sbt.xMain.run(Main.scala:71)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.ClassNotFoundException: sbt.SourcePosition
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at org.clapper.sbt.editsource.EditSourcePlugin$.projectSettings$lzycompute(EditSourcePlugin.scala:195)
[error]         at org.clapper.sbt.editsource.EditSourcePlugin$.projectSettings(EditSourcePlugin.scala:195)
[error]         at sbt.internal.Load$.$anonfun$resolveProject$3(Load.scala:1025)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error]         at scala.collection.immutable.List.flatMap(List.scala:352)
[error]         at sbt.internal.Load$.autoPluginSettings$1(Load.scala:1025)
[error]         at sbt.internal.Load$.expandSettings$1(Load.scala:1042)
[error]         at sbt.internal.Load$.$anonfun$resolveProject$10(Load.scala:1045)
[error]         at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
[error]         at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
[error]         at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
[error]         at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error]         at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error]         at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error]         at sbt.internal.Load$.expandSettings$1(Load.scala:1044)
[error]         at sbt.internal.Load$.$anonfun$resolveProject$1(Load.scala:1048)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.resolveProject(Load.scala:1014)
[error]         at sbt.internal.Load$.finalizeProject$1(Load.scala:864)
[error]         at sbt.internal.Load$.$anonfun$loadTransitive$10(Load.scala:915)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.loadTransitive(Load.scala:915)
[error]         at sbt.internal.Load$.loadProjects$1(Load.scala:714)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$10(Load.scala:717)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:717)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:677)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:154)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:219)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error]         at sbt.internal.Load$.loadAll(Load.scala:555)
[error]         at sbt.internal.Load$.loadURI(Load.scala:485)
[error]         at sbt.internal.Load$.load(Load.scala:464)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:249)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.apply(Load.scala:249)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:65)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:696)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:696)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:688)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error]         at sbt.State$$anon$1.process(State.scala:233)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:105)
[error]         at sbt.MainLoop$.run(MainLoop.scala:98)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error]         at sbt.StandardMain$.runManaged(Main.scala:104)
[error]         at sbt.xMain.run(Main.scala:71)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: sbt/SourcePosition

Thanks

**Comment by bmc** [comment]
Hoping to get to updating it this week sometime. Just got back from an overseas trip, so I'm still catching up.

**Comment by balintn** [comment]
Thank you very much!

**Comment by boldizsartoth** [comment]
Hi!
I would also be very interested in the sbt 1.0.2 / scala 2.12.* support!
Thank you very much in advance!

**Comment by chaasfr** [comment]
Hello, 
I just ran into the same issue, any update on the scala 2.12 support ? :)

Thanks in advance !

**Comment by bmc** [comment]
Sorry. I'm running behind on this. Working on it...

**Comment by bmc** [comment]
Fixed in v1.0.0, which you should be able to use now. That version is cross-built for SBT 1.0.x and SBT 0.13.x.
