### ISSUE TITLE
Test project does not build

### ISSUE THREAD

**Issue by jlgreen2012** [bmc/sbt-editsource#14]
Error: 
> sbt.ResolveException: unresolved dependency: org.clapper#grizzled-scala_2.10;1.0.10: not found. 

To reproduce: 

1. Clone repository
2. `cd src\testproject`
3. `sbt compile`

**Comment by jlgreen2012** [comment]
Was able to resolve by increasing sbt version to 0.13.16 and editing the sbt.build grizzled-scala version to one of the versions supported for scala 2.10: http://software.clapper.org/grizzled-scala/

**Comment by bmc** [comment]
Should be fixed now.
