### ISSUE TITLE
Add support to overwrite files

### ISSUE THREAD

**Issue by rogelio-blanco** [bmc/sbt-editsource#16]
Do you have support to replace variables from the file and overwrite it without creating a new file?

**Comment by bmc** [comment]
No. This plugin is a build tool plugin. The idea is that the source is a template that is used to generate the output file. The intent is that you put the source document somewhere in your source tree, and you maintain it along with your source code (which includes putting it under source control). At build time, you use this plugin to generate the filled-in output version, typically writing it somewhere under `target`.

Providing support for overwriting the original source file is out of scope.
